safe: true
lsi: false
source: .
baseurl: /ng-conferences.github.io
exclude:
  - CNAME
  - Dangerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - Rakefile
  - data_file_validator.rb
  - notes.txt
  - vendor
